import os

DATABASE_PWD = os.environ['DATABASE_PWD']
DATABASE_USER = os.environ['DATABASE_USER']
DATABASE_DB = os.environ['DATABASE_DB']
DATABASE_HOST = os.environ['DATABASE_HOST']
DATABASE_PORT = 5432
